// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/example/v1/example.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_proto_example_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_proto_example_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Example) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Example) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type FindAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRequest) Reset() {
	*x = FindAllRequest{}
	mi := &file_proto_example_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRequest) ProtoMessage() {}

func (x *FindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRequest.ProtoReflect.Descriptor instead.
func (*FindAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_v1_example_proto_rawDescGZIP(), []int{1}
}

type FindAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Example             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllResponse) Reset() {
	*x = FindAllResponse{}
	mi := &file_proto_example_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllResponse) ProtoMessage() {}

func (x *FindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllResponse.ProtoReflect.Descriptor instead.
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_v1_example_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllResponse) GetData() []*Example {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_example_v1_example_proto protoreflect.FileDescriptor

const file_proto_example_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/example/v1/example.proto\x12\n" +
	"example.v1\"L\n" +
	"\aExample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x10\n" +
	"\x0eFindAllRequest\":\n" +
	"\x0fFindAllResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.example.v1.ExampleR\x04data2T\n" +
	"\x0eExampleService\x12B\n" +
	"\aFindAll\x12\x1a.example.v1.FindAllRequest\x1a\x1b.example.v1.FindAllResponseB?Z=github.com/Kintamani/go-skeleton/internal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_proto_example_v1_example_proto_rawDescOnce sync.Once
	file_proto_example_v1_example_proto_rawDescData []byte
)

func file_proto_example_v1_example_proto_rawDescGZIP() []byte {
	file_proto_example_v1_example_proto_rawDescOnce.Do(func() {
		file_proto_example_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_example_v1_example_proto_rawDesc), len(file_proto_example_v1_example_proto_rawDesc)))
	})
	return file_proto_example_v1_example_proto_rawDescData
}

var file_proto_example_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_example_v1_example_proto_goTypes = []any{
	(*Example)(nil),         // 0: example.v1.Example
	(*FindAllRequest)(nil),  // 1: example.v1.FindAllRequest
	(*FindAllResponse)(nil), // 2: example.v1.FindAllResponse
}
var file_proto_example_v1_example_proto_depIdxs = []int32{
	0, // 0: example.v1.FindAllResponse.data:type_name -> example.v1.Example
	1, // 1: example.v1.ExampleService.FindAll:input_type -> example.v1.FindAllRequest
	2, // 2: example.v1.ExampleService.FindAll:output_type -> example.v1.FindAllResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_example_v1_example_proto_init() }
func file_proto_example_v1_example_proto_init() {
	if File_proto_example_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_example_v1_example_proto_rawDesc), len(file_proto_example_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_example_v1_example_proto_goTypes,
		DependencyIndexes: file_proto_example_v1_example_proto_depIdxs,
		MessageInfos:      file_proto_example_v1_example_proto_msgTypes,
	}.Build()
	File_proto_example_v1_example_proto = out.File
	file_proto_example_v1_example_proto_goTypes = nil
	file_proto_example_v1_example_proto_depIdxs = nil
}
