# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  # menjalankan perintah migrate
  migrate:
    desc: run migration sql
    cmds:
      - migrate -path db/migrations -database "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable" up
  
  # menjalankan perintah create migrate dengan format datetime
  create-migration-datetime:
    desc: create migration with datetime
    cmds:
      - migrate create -ext sql -dir db/migrations {{.name}}
  
  # menjalankan perintah create migrate dengan format sequence
  create-migration-sequence:
    desc: create migration with sequence number
    cmds:
      -  migrate create -ext sql -dir db/migrations -seq {{.name}}

  # generate protobuf
  proto:
    desc: generate protobuf files
    cmds:
      - PATH="$(go env GOPATH)/bin:$PATH" protoc --proto_path=. --go_out=. --go_opt=module=github.com/Kintamani/go-skeleton --go-grpc_out=. --go-grpc_opt=module=github.com/Kintamani/go-skeleton proto/example/v1/example.proto

